### PR TITLE
Setup grid cell sizes for groupUseEntireRow = false

### PR DESCRIPTION
**Pull request by cnrudd**
I was enthusiastically adding the app-wide Grid Sizing options in the Navbar App Menu for a client app, when I discovered that the Tiny, Compact, and Large sizes did not produce good group row sizes when the grid is using:

```
                    agOptions: {
                        groupUseEntireRow: false,
                        groupSuppressAutoColumn: true
                    }
```

which this client app uses A LOT.

This issue is reproducible in Toolbox in this branch: https://github.com/xh/toolbox/tree/groupUseEntireRow_false on the "Grouped Columns Grid", where I have set this agOptions config.

Here is a screenshot of the issue in toolbox:
gridCssError

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry.
- [x] Reviewed for breaking changes: no breaking changes.
- [x] Updated doc comments: not required.
- [x] Reviewed and tested on Mobile.
- [x] Created Toolbox branch: https://github.com/xh/toolbox/tree/groupUseEntireRow_false
**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Hi Tom -- Can you take a look at this one? Thanks

**Comment by TomTirapani** [comment]
This works, but I'm not sure it's the right approach. Using CSS to height rows is something we want to avoid, as the row height is actually quite variable.

We have two different sets of row heights for mobile and desktop: https://github.com/xh/hoist-react/blob/develop/cmp/ag-grid/AgGrid.js#L90-L104. Furthermore, we allow apps to override these, and there's also the `GridModel.groupRowHeight`, `Column.rowHeight` and `Column.autoHeight` configs to take into account. We can't really rely on any particular row height in CSS.

For normal cells, we took the approach of vertically centering the cells to handle this variability: https://github.com/xh/hoist-react/blob/develop/cmp/ag-grid/AgGrid.scss#L180-L184. Could we take a similar approach with the group cells when `groupUseEntireRow: false` ?

**Comment by cnrudd** [comment]
@TomTirapani thanks for the pointers.  looking into vertical centering solution now.

**Comment by cnrudd** [comment]
@TomTirapani I think this one line change solution in the latest commit might be the one.  Thanks!
Colin

**Comment by TomTirapani** [comment]
Looks great to me!

**Comment by amcclain** [comment]
Note that the CL entry here ended up bucketed under the last version - easy to happen with a PR that stays open across a release.  Will fix now.

**Pull request merged**
