### PR TITLE
Upgrade Onsen to latest versions

### PR DESCRIPTION
**Pull request by TomTirapani**
onsenui: 2.11.1 > 2.12.0
react-onsenui: 1.11.5 > 1.12.0

See issue: https://github.com/xh/hoist-react/issues/3014

As discussed in the ticket, there is a required workaround for an issue with Onsen serialising components in kit/onsen/index.js. The PR works, but I wonder if there might be a better approach to ensuring HoistModels never get passed to Onsen components? Let's discuss.

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by TomTirapani** [comment]
Updated this to the latest, and unfortunately its not compatible with latest webpack - the webpack sass-loader complains about typos in their CSS:

Screenshot 2022-08-11 at 11 48 42

**Comment by lbwexler** [comment]
Now a Draft, as we need to look into the CSS issue.  

Regarding the custom elem factory, we could consider building in to ElementFactory the code to omit HoistModels from props whenever the component itself is not a HoistComponent.    

On the other hand, am loathe to add anything to ElementFactory that is more specific to Hoist -- really would like to see it stay as an independent layer that really could be broken out from Hoist 'one day'

**Comment by lbwexler** [comment]
If we do decide to cleanse the props only for Onsen component, I wonder if we could come up with some kind of inner wrapper for all the Onsen Components that would not require us to publicize normalizeArgs and override elemFactory.

**Comment by TomTirapani** [comment]
Great idea about using an inner wrapper to cleanse the props of model, can give that a try.

The CSS issue is harder, and I really don't see many options forward besides either submitting a PR to Onsen and / or using our own fork. :|

**Comment by TomTirapani** [comment]
I've updated this branch to the latest hoist and onsen versions, and think its ready for review / merge

**Pull request merged**
