### PR TITLE
Grid export enhancements

### PR DESCRIPTION
**Pull request by petradish**
+ Add `exportOptions.timeout` soft config
+ Fix: Export column order based on sort order of `exportOptions.columns`

See Hoist-Core PR: https://github.com/xh/hoist-core/pull/200

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [N/A ] Reviewed and tested on Mobile, or determined not required.
- [N/A] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by TomTirapani** [comment]
Looks great! Awesome that we were able to get rid of the `streamingCellThreshold` concept by reusing those group background styles.

Overall looks great, but I'm not clear on the need for downgrading tree exports to leaf rows given the hoist-core change. What is the strain of producing tree grids now that we're caching the group styles? Is it simply a way to reduce the cell count?

**Comment by petradish** [comment]
Hi Tom! It is really a lot longer to create a tree-grid as we are currently doing it:
2021-07-08 15:38:05 | GridExportImplService [DEBUG] | Generating Export | export | 50002 rows | 6 cols | 1 depth | petra@xh.io | completed | 27349ms
2021-07-08 15:40:11 | GridExportImplService [DEBUG] | Generating Export | export | 50002 rows | 6 cols | 2 depth | petra@xh.io | completed | 109783ms
I just enhanced our debug to show that for the exact same row and col count (using the Test Grid in admin), just an additional level of depth will take 4 times as long. I think as you add more depth it might take even longer... not 100% sure what is causing this though.

**Comment by lbwexler** [comment]
+  we clearly want to remove the warning around `streamingCellThreshold` -- this has already been changed in Hoist Core
+ We also clearly want to take  column ordering fix.
+ Not sure about fixing the timeout.  Perhaps that should also be configurable in the soft config?
+ Not sure about degrading to just showing the leaves when above the new threshold.  Would an application generally want that?  What about cases where the leaves are not all at the same depth?  (we have grids like this.)

**Comment by petradish** [comment]
Hi @lbwexler could you please review these changes we discussed yesterday? Unwinding the change in hoist-core now

**Comment by lbwexler** [comment]
Petra and I discussed this -- want to think a bit more about the timeout.  

+ Should this be per call?  Default in the config?
+ Also -- if we are contemplating long-running exports, do we need to show some kind of affordance indicating the export is in progress?  Should we allow specifying modal exports?  Petra has noted that the current setup makes it very easy to generate multiple exports and use up all the request threads on a tab.

**Pull request merged**
