### PR TITLE
Move inline scripts into standalone file.

### PR DESCRIPTION
**Pull request by TomTirapani**
See issue #2062.
See corresponding hoist-dev-utils PR here: https://github.com/xh/hoist-dev-utils/pull/27

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by amcclain** [comment]
Hi Tom - thanks for looking at this!

Here is my concern (not yet verified) with this approach... The goal of this script is to cleanly identify older browsers that can't run the code at all and to display a basic inline error message. With this approach, my understanding is that the little outdated-browser detection script will end up bundled in the same file as the rest fo the codebase - or at least some common chunk of it. Is it possible then that an older browser would load and attempt to parse that first chunk and fail to even get to the execution step due to unknown keywords or syntax being present in the file?

I had been thinking that we would need a process, distinct from the main bundles, that would bring this file into the HTML source as its own standalone script tag, to be loaded/parsed/executed before any bundles.

But if this works I don't want to over-complicate things. Were you able to test, or does the concern above make sense in terms of requiring some testing to see how it behaves?

**Comment by lbwexler** [comment]
Guys -- I suspect this might work -- but to answer the question we really just need to test this on IE11, which is the best example of a browser we are trying to defeat with it.  

I am hoping that the main problem is just that mobx 5 calls `new Proxy()` when it actually executes, but this script will execute first and prevents that.

**Comment by lbwexler** [comment]
@haynesjm42 -- can you try this PR out on your windows machine with IE 11 and let us know if cleanly yields the error message we are trying to produce?

**Comment by haynesjm42** [comment]
This is what I got in IE11 - looks good!

image

**Comment by lbwexler** [comment]
Thanks John!

**Comment by lbwexler** [comment]
Am going to merge this, based on atm's comments,  the successful test, and our desire not to get too caught up on support for unknown legacy browsers....

**Comment by amcclain** [comment]
Thanks for testing/merging - just catching up here apologies am a bit behind. 

- @haynesjm42 just checking, did you use a locally linked version of dev-utils to test? 
- I will update Toolbox to use the dev-utils snapshot so we can ensure we're testing this change there - right now it's still on the prior released version so a bit of a mismatch.
- To that point, I think we need a changelog entry highlighting that the current hoist-react release should be paired with a dev-utils release which we need to do.
- But before that I wanted to revisit small question of possible confusion over `bootstrap.js` name - @lbwexler I think you had raised that.  Should we rename the file in `/static/` to something like `preflight-checks.js` (or any other suggestions - it also sets the starting timestamp)?
- We should also add a comment to `/static/README.md` as otherwise the new file is a bit of a mystery.  Again wanted to confirm the name first.

Sorry for being behind here - these dev-utils related/coordinated changes sometimes have a few wrinkles so I didn't want to miss anything.

**Comment by amcclain** [comment]
I updated toolbox-dev to put it back on snapshot for hoist-react and and hoist-dev-utils - 

if you look at the source and the bundles I don't know / think that the new preflight code is the first JS run on the page. Let me know if I am missing something here?

**Comment by haynesjm42** [comment]
When I tested I had copied the entirety of webpack.config.js from the branch on hoist-dev-util and ran locally, then opened in IE.

Just tried opening toolbox-dev in IE11 and am not getting the unsupported browser message - so it appears that I did not have something correct when testing or that testing approach was flawed :(

**Comment by amcclain** [comment]
Potentially related to how the bundles/chunks are built and ordered in production bundling mode vs. dev-time mode - or something similar.  Thanks for testing again with the deployed version.

We can revisit some more early next week w.r.t. different options for getting the bootstrap file into the source but maybe not including in the core bundles, if that is indeed the issue...

**Comment by amcclain** [comment]
I think I have a working approach. Just-released hoist-react 36.1.0 includes both inline and no-inline versions of the index.html template.  I also renamed the `static/bootstrap.js` to `preflight.js` as a slightly more descriptive / non-overlapping name.

https://github.com/xh/hoist-react/commit/bfa46360f57f9f4246c8bd46a2fa720d8050167e

This way hoist-react should have the resources to work with either the existing dev-utils versions or a new one.  For the new one, I used the `CopyWebpackPlugin` we already had to copy the preflight script into `/public/` within the build output. Then used new `HtmlWebpackTagsPlugin` to inject a script tag w/cache busting hash into the generated HTML output, before all other bundle script tags:

https://github.com/xh/hoist-dev-utils/commit/3b9b2b61879bd314cf9f140a3fc267808353d042

In my test Win10 VM this now shows the error message correctly in IE11 - John if you can test again that would be great. And I was able to tighten up the CSP header for Toolbox to restrict any inline script tags, which was the ultimate goal. 

Hopefully all set with this for the time being!

**Pull request merged**
