### PR TITLE
Don't apply default Select.filterFn in async mode

### LINKED ISSUE #2192: Select default filterFn incorrectly applied in async mode
I noticed that our filter chooser was no longer showing it's "x of y results shown" message when suggestions are truncated.

You can replicate on the GitHub activity widget by typing "Author =" - a list of suggestions are shown, but you don't see the truncation message.

This was caused by the recent update to Select to supply a smarter default filterFn. That filter is being applied even in async mode, so it's run against the results of the `queryFn`, which is not desired.

### PR DESCRIPTION
**Pull request by amcclain**
+ Fixes #2192

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by amcclain** [comment]
See ticket for details on replicating and how this manifested in FilterChooser.
Note that mobile Select does not support async, so N/A there.

**Comment by amcclain** [comment]
@lbwexler I'm going to go ahead and merge this as I would like to get it into a snapshot for a client app release prior to additional QA next week. Of course please give a shout if anything looks off or in need of further investigation!

**Comment by lbwexler** [comment]
looks good

**Comment by lbwexler** [comment]
not critical, but had to look up my "order of precedence" to see that && has precedence over ||.  Might benefit from an explicit additional set of parenthesis, but this looks to be doing what you intend

**Pull request merged**
