### PR TITLE
Use `xhExportConfig` config to manage export toasts.

### PR DESCRIPTION
**Pull request by TomTirapani**
See issue: https://github.com/xh/hoist-core/issues/74
See corresponding hoist-core pr: https://github.com/xh/hoist-core/pull/137

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
This looks great, but without a handling of the when the config is not present, will require a more modern version of hoist core to be present that guarantees the presence of the config.

Its easy enough to add the key on the fly of course, but this looks like it has the potential to be a silent export killer.

Maybe wait until hoist core is in the wild for a bit more before merging this one?  there is no rush.

**Comment by lbwexler** [comment]
I will go ahead and merge this, and add to the changelog a mention of it, so app updaters can throw in the config if needed.

**Comment by TomTirapani** [comment]
Thanks for merging Lee. I also expected us to wait until hoist-core was out (especially in client apps) before merging this.

Perhaps we could quickly some fallback handling where we access these config props, so it won't fail if the key is missing.

**Comment by TomTirapani** [comment]
Added a quick PR here to not break exports if they run don't yet have the hoist-core update:
https://github.com/xh/hoist-react/pull/1850

**Pull request merged**
