### PR TITLE
Support line breaks in default `FormField` read-only renderer

### PR DESCRIPTION
**Pull request by ghsolomon**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Interesting fix, and now I know that "pre" stands for "preserve"

**Comment by lbwexler** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

Interested to know how we landed on `pre-wrap` vs. the other options that handle line-breaks

**Comment by ghsolomon** [comment]
This article does a pretty good job of illustrating the different options:
https://css-tricks.com/almanac/properties/w/whitespace/

**Comment by TomTirapani** [comment]
Looks good to me.

I think `pre-wrap` is the right option, most closely mirrors the behaviour of textarea w.r.t to new lines and tabs.

**Pull request merged**
