### PR TITLE
Fix Summary record handling in tooltip

### PR DESCRIPTION
**Pull request by lbwexler**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
This one is a little strange, but think we should truly own the way we do these tooltips and its relationship to our records.

**Review by petradish — APPROVED** [review]

**Review by TomTirapani — APPROVED** [review]
This makes sense - happy to see it doesn't affect the value passed to tooltipSpec.

Am I right in understanding we never really expect the tooltipValueGetter to be used outside of our tooltip render function? (since people should be using the provided `tooltip`|`tooltipElement` props?)

**Comment by amcclain** [comment]
I believe this was a pre-existing issue and _not_ something introduced by this fix, but FYI I just pushed a tweak/fix in 62daf210d92ea81444615e86a3bfd4d6a1d93ea8 to defend against records with an undefined value throwing (badly!) on hover / tip show.

**Comment by lbwexler** [comment]
great fix!

**Pull request merged**
