### PR TITLE
Icon refactor

### PR DESCRIPTION
**Pull request by lbwexler**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [X] Added CHANGELOG entry, or determined not required.
- [X] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [X] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [X] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by TomTirapani** [comment]
Looks great!

Should we remove the enumerated `Icon.add()`, etc., in favour of using `iconName`? Right now we have some icons that use the old method and some that use the new factory.

Also, did we consider removing the export for `convertToSvg`, to enforce using the new `asSvg`?

(I know the above would be breaking changes, and perhaps we want to avoid that - I'm just thinking about enforcing a single standard across apps)

**Comment by lbwexler** [comment]
thanks tom --

+ I think the enumerated ones are a great convenience feature with
intellisense,
+ We still need convertToSvg internally in hoist -- but I can definitely
make it clear that applications
should not typically use it.

**Comment by lbwexler** [comment]
Got a few more cleanups here.  Please do not merge

**Comment by amcclain** [comment]
Hi - small follow-on fix here 6ebd4c212a1e47a1262d998b73b17cdc2dfbe2d5 - please take a look to ensure this is reasonably anytime. 

I also tweaked the changelog to note the removal of `fontAwesomeIcon()` - replacement a great improvement: 9a46e42e64d1e2961acc48bd75eb684cf1afb063

**Pull request merged**
