### PR TITLE
Null displayName on FieldModel should default to generated displayName

### LINKED ISSUE #2746: Form field validation message should provide better default if `FieldModel.displayName` is null
Contrived Example:
Screen Shot 2021-10-21 at 11 50 19 AM

`displayName` for this field is `null` to hide its label by default. However, the required validation message that appears stringifies its null value.

### PR DESCRIPTION
**Pull request by saba-mo**
Closes #2746 

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by saba-mo** [comment]
Hi @lbwexler, I've submitted this as a draft because I'm wondering if there's a cleaner way to check for a null displayName since it's not entirely consistent right now.

**Comment by lbwexler** [comment]
Hi Saba -- thanks for taking a first cut of this.  It forced me to look at it carefully.  Seeing it made me rethink the ticket -- added some comments for @petradish  to consider

**Comment by saba-mo** [comment]
The display name will be generated if the user sets it to null or undefined. Does this warrant a changelog message? It seems pretty minor but if we think devs are setting it to null, it might need a breaking change note.

**Comment by lbwexler** [comment]
I don't think this should to be considered a breaking change -- any developer doing this was relying on an undocumented hack, for which we think the API has a proper solution.  Also, think the consequences of this showing a formerly hidden label are relatively minimal

**Pull request merged**
