### PR TITLE
React grid layout upgrade

### PR DESCRIPTION
**Pull request by leogretz2**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Hi @ghsolomon -- Can you update this to version 1.4.4 and ensure bugs are fixed and everything in order?
Would like to merge and close this out after today's role release.

**Comment by ghsolomon** [comment]
> Hi @ghsolomon -- Can you update this to version 1.4.4 and ensure bugs are fixed and everything in order? Would like to merge and close this out after today's role release.

Took a look at this, and v.1.4.4 has that bad bug we were seeing that caused widgets to snap to the top-left corner upon any drag action. 

Here is a link to the (currently still open) issue: https://github.com/react-grid-layout/react-grid-layout/issues/1990

**Comment by lbwexler** [comment]
Converting this to DRAFT -- will revisit as soon as we get a new release

**Comment by lbwexler** [comment]
@ghsolomon -- looks like the linked ticket now describes a simple workaround that would let us move forward to the latest version -- can you take a look?

**Comment by ghsolomon** [comment]
> @ghsolomon -- looks like the linked ticket now describes a simple workaround that would let us move forward to the latest version -- can you take a look?

Nice! New PR: https://github.com/xh/hoist-react/pull/3880

**Pull request closed without merging**
