### PR TITLE
XH.getActiveModels()

### PR DESCRIPTION
**Pull request by lbwexler**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [X ] Caught up with `develop` branch as of last change.
- [X] Added CHANGELOG entry, or determined not required.
- [X] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [X] Updated doc comments / prop-types, or determined not required.
- [X] Reviewed and tested on Mobile, or determined not required.
- [X] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Review by ghsolomon — COMMENTED** [review]
Looks really good!  And I like your idea of updating `matchesSelector()` so you can more easily provide a string classname.  I played with that a bit- see what you think:

```
    matchesSelector(selector, acceptWildcard = false) {
        if (selector === '*') return acceptWildcard;
        if (isString(selector)) return this.constructor.name === selector;
        if (!isFunction(selector)) return false;

        // 1) selector is a constructor function/class
        if (selector.isHoistModel) {
            return this instanceof selector;
        }

        // 2) selector is a callable function, call for either a boolean or a constructor function/class
        const result = selector(this);
        if (isString(result)) return this.constructor.name === result;
        return isFunction(result) && result.isHoistModel ?
            this instanceof result :
            !!result;
    }
```

**Comment by lbwexler** [comment]
what you propose looks good, but my only concern there was that what if we later introduce a name property on models and want to allow searching by name.  That will also be a string -- am nervous about right now saying that any string will just be considered to be a classname.

would it be too hacky to have a string be interpreted as either a name or a class name?  Or should we have some kind of object form e.g. {name: 'mymodel'}, {class: 'FooModel'}, etc. that supports a lodash like flexibility?

**Comment by amcclain** [comment]
A few incremental additions I might propose:

* Should we nest this feature under a singleton class or service on which we could hang additional future functionality - something like `XH.ModelRegistry`?
* Could we add a ready-to-getter that returns models grouped by ctor name, especially for easy and repeated console access.
* Could we add a `stats` object that provided some simple counts of both total (life of app) and currently active models, also grouped by ctor name? I don't know if or how this would specifically be useful, but it would admittedly be interesting, and might help keep an eye out for memory leaks or things like reactions firing much more often than intended and creating huge numbers of models.
* What's the intention with the proposed name property?  Is this a class-level property, distinct from the ctor name, or more like an id or key to identify an individual model instance?

**Comment by ghsolomon** [comment]
> what you propose looks good, but my only concern there was that what if we later introduce a name property on models and want to allow searching by name. That will also be a string -- am nervous about right now saying that any string will just be considered to be a classname.
> 
> would it be too hacky to have a string be interpreted as either a name or a class name? Or should we have some kind of object form e.g. {name: 'mymodel'}, {class: 'FooModel'}, etc. that supports a lodash like flexibility?

That makes sense - I had the same thought about being able to pass an object like you suggested.

Also thought we could provide a helper function like `const ofClassNamed = className => it => it.constructor.name === className` so you could just write `matchesSelector(ofClassNamed('MyClass'))` but that doesn't really help when doing this from the console

**Comment by lbwexler** [comment]
@amcclain -- thanks for the comments -- Greg and I discussed in detail.
We think the ideas all make sense and could be future extensions, but none of them would be made impossible by the simple first step we have here.  We are only introducing a single API addition to XH right now, that will be easy to continue supporting no matter what direction we go

Regarding searching for models instances by 'name', we can discuss further what I am thinking, but its all pretty speculative  and I don't think it needs to hold up this PR

**Pull request merged**
