### PR TITLE
Remove remaining class-based components from internal Hoist code

### PR DESCRIPTION
**Pull request by lbwexler**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Seperated this out from some of the API disruptions related to mobx6.  Would like to go forward with this.

**Comment by lbwexler** [comment]
Tom and I reviewed this, and it reminded me that we should highlight the change that this relaxes the requirement that any  model for a functional component be a `HoistModel`.

The class-based component did not require that, and I don't think the functional component needs to either.  Not so uncommon for users to want to bind their inputs to simpler observable "models"

**Comment by cnrudd** [comment]
@lbwexler I think something in this merge commit has affected the way refs are handled.

For example I notice that logic like this:
      ```return this.selectRef.current?.reactSelectRef?.current;```

no longer returns the the ReactSelect component.  It just returns the DOM element at this.selectRef.current

If i check out the prior commit: 06554433c0230a543d57354ef93c28bd80522554, the line above works.

**Comment by lbwexler** [comment]
Will fix.  Thanks for catching!

**Comment by lbwexler** [comment]
So this is a great catch.  Am hoping that this is isolated to reactSelectRef, but please read below.

It's true -- the 'refs' for all the inputs were changed -- they now refer to the top level dom object of the component, rather than the component instance itself.  This is just the 'default' for refs for all functional components.  The idea is that there is no longer really a component object available that external instances should be manipulating directly.  It should all be done with props.

Are there other 'properties/methods' on our class based inputs that we were using from the  outside?  Do we poke at their internal methods to get them to close  Did I miss something here? If that is the case, I could restore the existing behavior on refs using `useImperativeHandle` to return the underlying model as the 'ref'.  But I would rather not.

If its just reactSelectRef, would like to go ahead and just make that a new first level prop on the functional component that we pass through.

Might have a similar issue on DateInput, however that apparently has  
     inputRef = createObservableRef();
    buttonRef = createObservableRef();
    popoverRef = createObservableRef();

Agree there is an issue here we have to address ASAP

**Pull request merged**
