### PR TITLE
Make Mask, ErrorMessage, LoadingIndicator and TreeMap cross-platform

### PR DESCRIPTION
**Pull request by TomTirapani**
See issue: https://github.com/xh/hoist-react/issues/3818
See Toolbox PR: https://github.com/xh/toolbox/pull/747

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Is this completely driven by mask and errorMessage?

**Comment by lbwexler** [comment]
Tom and I discussed this -- Tom is going to take another pass and see if he can make mask and errorMessage cross-platform -- this would be more of a breaking change, but could give us much more bang for the buck, and would make a cross-platform version of this (and maybe other components) trivial.

**Comment by TomTirapani** [comment]
Updated this and the toolbox PR to make ErrorMessage and Mask cross-platform, and therefore not require two implementations of TreeMap / SplitMap.

Also made LoadingIndicator cross-platform as it was low-hanging fruit

**Review by lbwexler — COMMENTED** [review]
I am all for this -- thanks tom!

**Review by lbwexler — APPROVED** [review]

**Comment by lbwexler** [comment]
@amcclain -- are you ok with this somewhat noisy breaking change to imports?  I think its worth it.

**Comment by amcclain** [comment]
If you guys are all good with it, I am too.  Have not reviewed this change myself, but I've been bitten a few times with errorMessage not being cross-platform, so am very happy to see a resolution to that and all for it.

**Pull request merged**
