### PR TITLE
GroupingChooser tweaks for usability

### PR DESCRIPTION
**Pull request by amcclain**
+ Auto-expand add dim select upon show.
+ Add text to toolbar buttons to make them easier click targets.
+ If add dim button clicked and only one dim remains to add, add it immediately instead of showing select.
+ Show remove dim button on row hover only, add danger intent for general consistency.

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [ ] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by amcclain** [comment]
After a few weeks of using our new grouping chooser, I would like to propose the included (minor) changes in the name of greater usability. 

I know that we discussed the auto-expand of the "add dim" select when we first released this component and decided to go without it, to avoid any surprising or over-eager interactions. However I must say that with regular use, that extra click to expand the select bugs me every time, and I almost never want to type an option.

I also find that I have a difficult time quickly hitting the Add button - I'd really like to lengthen that text to make it a bigger target, and I thought it made sense to add text to the "Apply" button as well (there you can click the underlying mask to apply, but that's not too obvious).  I don't think we need to be so minimal in these UI elements.  (I did try OK and Save as alternate text options for that button, but Apply still strikes me as the most appropriate.)

**Comment by amcclain** [comment]
Here's what this rev looks like, for convenience.  Also, I didn't apply these changes to mobile as I wanted to get feedback on desktop first, but I think it would make sense to keep consistent and I can make those updates whenever we agree on taking/leaving changes. (Hopefully taking 😄 )

Screen Shot 2021-02-03 at 6 45 56 AM

**Comment by lbwexler** [comment]
I am all for these changes

**Comment by TomTirapani** [comment]
Just took a look at this; I think it's a huge improvement :)

Thanks for making these changes, I'm all for taking them. Only thing I can think of is maybe changing the `Add Level` label to just `Add`, the `Level` there feels a bit redundant.

**Comment by lbwexler** [comment]
I am making the change I mentioned to handle the empty case.

**Comment by lbwexler** [comment]
I applied the changes that made sense on mobile, added the empty display to the popover, and made a few additional tweaks.

Not sure about the new text on the mobile buttons -- seems a little bit clunkier in that context, but will let you be the judge ATM.

Thanks!

**Pull request merged**
