### PR TITLE
Add option to show counts in column headers

### PR DESCRIPTION
**Pull request by peterjcoffman**
Hoist P/R Checklist
-------------------

Review and check off the below. Items that do not apply can also be checked off to indicate they
have been considered. If unclear if a step is relevant, please leave unchecked and note in comments.

- [x] Up to date with `develop` branch as of last change.
- [ ] Ready for review (or open as a draft PR / add `wip` label).
- [x] Added CHANGELOG entry (or N/A)
- [ ] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [x] Updated doc comments / prop-types (or N/A)
- [ ] Reviewed and tested on Mobile (or N/A)
- [ ] Created Toolbox branch / PR (link provided here, or N/A)

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by peterjcoffman** [comment]
I'm not sure whether or not we should save showCounts on the model. I don't use it outside the constructor.

**Comment by lbwexler** [comment]
I think this is correct visually, in that we don't need to offer a units label  (e.g. Visible (7 Columns )).
Let me know if you disagree John.

**Comment by haynesjm42** [comment]
I agree, I don't think adding a units label would be desired in most use-cases (certainly not in the one which prompted this ticket)

**Comment by lbwexler** [comment]
Do we all love the new count so much that we want to default it to true, including in our column chooser?

**Pull request merged**
