### PR TITLE
Add a 'lossless' number formatter

### PR DESCRIPTION
**Pull request by peterjcoffman**
I additionally created and exposed a 'shorthand' number formatter.

Hoist P/R Checklist
-------------------

Review and check off the below. Items that do not apply can also be checked off to indicate they
have been considered. If unclear if a step is relevant, please leave unchecked and note in comments.

- [x] Up to date with `develop` branch as of last change.
- [x] Ready for review (or open as a draft PR / add `wip` label).
- [x] Added CHANGELOG entry (or N/A)
- [x] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [x] Updated doc comments / prop-types (or N/A)
- [x] Reviewed and tested on Mobile (or N/A)
- [x] Created Toolbox branch / PR (link provided here, or N/A)
https://github.com/xh/toolbox/pull/310

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by peterjcoffman** [comment]
Relates to this issue: 
https://github.com/xh/hoist-react/issues/438

**Comment by lbwexler** [comment]
This looks promising, although am not sure I fully understand, I do have some suggestions:

1) The proposed `formatShorthand` could also have it take an additional argument `allowable units` which was an array of the form ['t',  'b',  'm' , 'k'] -- this would meet Anselm's stated requirement that sometimes we do *not* want to use thousands (k) as an option.  We also might call it `formatCompactNumber`, as this this would be analogous to `formatCompactDate` (although I don't feel strongly on this point).
 
2) I admit that I don't fully understand the current implementation of  `formatLossless`, but am wondering if its functionality could be folded into the `formatCompactNumber` by adding an argument of the form `allowRounding` and using the existing "precision" argument or adding a new "maxPrecision" argument.   It seems like it really is a variant of the same method, e.g. compacting the representation of a number, as much as appropriate given certain constraints.

2) Whatever we come up with, we need documentation added to describe this method or methids (e.g. "Will use the largest possible unit provided such that the resulting number is greater than or equal to 1, etc. ")

**Comment by peterjcoffman** [comment]
@lbwexler 

Regarding the points you raised:

1. I'll ask Anselm what behavior he wants. I'm not sure what he's actually asking for.

2. fmtShorthand is not requested in the issue. It is really a helper function for fmtLossless, which I thought seemed useful and general enough to expose. The difference is that fmtShorthand will _always_ use the largest possible unit, while fmtLossless will only do so if it can remove several trailing zeroes by doing so.

3. I added some better documentation.

**Comment by amcclain** [comment]
Closing as outdated / no action taken.

**Pull request closed without merging**
