### PR TITLE
Ag-Grid -> 29.1.0

### LINKED ISSUE #3285: Upgrade Ag-Grid to 29
https://www.ag-grid.com/changelog/?fixVersion=29.0.0

### PR DESCRIPTION
**Pull request by haynesjm42**
Fixes #3285 

Toolbox PR: https://github.com/xh/toolbox/pull/637

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [ ] Caught up with `develop` branch as of last change.
- [ ] Added CHANGELOG entry, or determined not required.
- [ ] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [ ] Updated doc comments / prop-types, or determined not required.
- [ ] Reviewed and tested on Mobile, or determined not required.
- [ ] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by haynesjm42** [comment]
Found 1 regression so far - looks like setting the header height to 0 is now interpreted as a falsey value and resulting in the header height using the default height from the theme - added handling to set this via css instead but we might consider reporting this and getting it fixed in 29.1.0 - does not seem like correct behavior

**Comment by lbwexler** [comment]
So 29.1.0 is out with a large number of fixes, including one related to header height.  Would like to try this and see if we can undo John's workaround.

**Comment by PeteDarinzo** [comment]
AG Grid 29.1.0 does fix the issue of 0 header height getting the default height. 

New regression: all rows now get a style attribute `--ag-line-height: -1px;`, causing all grids to appear to empty even though data is loaded. AG Grid 28's attribute was `--ag-line-height: 26px;`, still determining cause.

**Comment by PeteDarinzo** [comment]
Row height regression corrected by removing `height: auto` from the AG Grid outer div in AgGrid stylesheet. This outer div has a default height of 100%, overriding to auto causes collapse of the content spans.

@haynesjm42 agrees that `height: auto` is obsolete and safe to remove. Testing done on all Toolbox desktop and mobile grids confirms that deletion is safe, and regression is fixed.

Detailed analysis:

When setting line height, AG Grid selects the minimum of the height returned from the grid's `getRowHeight` method and a default row height, then subtracts 2. The default row height is calculated from the theme, or returns a default value. The calculation method inserts the html element into the grid and uses `window.getComputedStyle` to determine the height property for the element. In the case of `height: auto`, the calculated value is `1px`. This results in the `--ag-line-height` being set to `-1px`. The height value is correctly calculated in the case of `height: 100%`. The conclusion drawn is that when `height: auto`, the grid html element is in a collapsed state due to no data being loaded, therefore no height required.

**Comment by lbwexler** [comment]
Thanks for the careful analysis and testing here.  We will merge and try to shake this out further before our v56 release.  Easy enough to rollback if needed.

**Pull request merged**
