### PR TITLE
FetchService.defaultTimeout

### PR DESCRIPTION
**Pull request by lbwexler**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [X] Caught up with `develop` branch as of last change.
- [X] Added CHANGELOG entry, or determined not required.
- [X] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [X] Updated doc comments / prop-types, or determined not required.
- [X] Reviewed and tested on Mobile, or determined not required.
- [X] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by cnrudd** [comment]
This looks great.  Just so I am clear about it, if a dev wanted to set a longer timeout for all app calls but not change the default for all Hoist calls, they would now do this:

```
export class AppCustomFetchSvc extends FetchService {}
```

then instantiate in appModel:
```
    async initAsync() {
        await XH.installServicesAsync(
            AppCustomFetchSvc
        );
       XH.appCustomFetchSvc.setDefaultTimeout(2 * MINUTES);
```

Works for me.

**Review by cnrudd — APPROVED** [review]
Left one comment in main conversation block.

**Comment by lbwexler** [comment]
Colin -- you can also call that method in the constructor of your overridden class.

**Comment by cnrudd** [comment]
> Colin -- you can also call that method in the constructor of your overridden class.

@lbwexler oh right!  nicer.

**Pull request merged**
