### PR TITLE
Fix fmtNumber's support for large ints and floats.

### PR DESCRIPTION
**Pull request by cnrudd**
This PR resolves this issue: https://github.com/xh/hoist-react/issues/2780

This corresponding toolbox branch https://github.com/xh/toolbox/pull/541 should also be merged, it adds a few tests that help confirm this fix is working.

Some helpful reference links:
https://mikemcl.github.io/bignumber.js/#
https://stackoverflow.com/questions/45929493/node-js-maximum-safe-floating-point-number

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile: did not yet test on mobile, not expecting any issues.  
- [x] Created Toolbox branch.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by cnrudd** [comment]
### Instances of formatConfig used in client apps:
**Easy replacements:**
formatConfig: {thousandSeparated: true}        // not needed.  withCommas defaults to true
formatConfig: {mantissa: 0, thousandSeparated: false}    // precision: 0, withCommas: false
formatConfig: {thousandSeparated: false, mantissa: 1} // precision: 1, withCommas: false

**might need to add our own 'average' config to replace this: http://numbrojs.com/format.html#average**
formatConfig: {average: true, mantissa: 3, trimMantissa: true}
formatConfig: {average: true, mantissa: 1, optionalMantissa: true}

**Comment by cnrudd** [comment]
I've confirmed that this change is working well, producing correct numbers in client app.

**Comment by cnrudd** [comment]
Hi @petradish  & @lbwexler ,  
after discussions about this PR with each of you last night, I made a number of changes this morning that I think address the concerns each of you brought up.

Petra: I've taken your suggestion of declaring the full FORMAT config object and modifying its comma key.  The code also no longer modifies the FORMAT of a BN instance.  The format is now passed as an argument to the toFormat function.   This change improves in the process in 2 ways:
1. There is no risk of some earlier modification to a BN instance's FORMAT polluting our own format requirements
2. We do not modify any BN instance's FORMAT.

Lee: I've found that it wasn't necessary to do any constructor cloning, since the format can be passed as an argument.  So, the use of BN is more straightforward and easier to understand now.


Another change I did was work the use of BN more completely into all of the implementation functions.  This makes the diff look more significant, but I think this is a necessary change if we're going to go this way at all.

**Comment by lbwexler** [comment]
Thanks Colin.  Would like to hold off on further work on this, until we decide that we actually want to support BigNumber in Hoist or just used by clients that really need it directly in their applications.

**Pull request closed without merging**
