### PR TITLE
TreeMap & SplitTreeMap resizing

### PR DESCRIPTION
**Pull request by TomTirapani**
Mask TreeMap & SplitTreeMap when doing 'significant' resizing, to hide the rendered whitespace.

Use a heuristic to determine if the amount of whitespace is 'significant'. Whitespace is deemed to be significant if it extends beyond 50px in either direction.

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Tom and I reviewed.  There is a regression to the label clipping/hiding that he will look at next week.
We will also change the name of the model flag to `isMasking`

**Review by lbwexler — COMMENTED** [review]
Approved, pending fix to regression, rename

**Comment by TomTirapani** [comment]
I spent a while looking into the label visibility regression.

Our previous masking approach included hiding the chart SVG with CSS. However, it seems that any labels that are reused after the masking are then unable to be sized - their dimensions are always zero, and I couldn't figure out a way to get the true dimensions.

I tried a different approach to the masking, where we instead show a mask *over* the chart rather than modifying the chart styles. This approach does not modify the chart component at all, and thus restores the label visibility functionality.

**Comment by lbwexler** [comment]
👍

**Pull request merged**
