### PR TITLE
Mask login panel while submitting

### PR DESCRIPTION
**Pull request by amcclain**
+ This is almost always instant during local development, but can take a bit of time on a slower connection.
+ Mask should also help to avoid double-submits, which can result in app init being called twice.

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by amcclain** [comment]
I didn't think a changelog entry was necessary here, but could add if desired.

**Comment by TomTirapani** [comment]
Looks good - clear improvement to actually wait for the login request.

My only thought is if we should take this opportunity to use a FormModel and field validation here, so we get the red validation around the missing fields? These login prompts predate that functionality.

It's not that I think users are going to be confused about why the simple login form is disabled, but more about providing a feature rich first impression.

**Comment by lbwexler** [comment]
Tom -- I think its a great suggestion, but I am going to merge this now in any case
+ Its really independent of this fix.
+ We are actually looking to tear this whole login out (for non-admins), so don't want to spend anytime on this right now.

**Comment by amcclain** [comment]
Thanks for merging.  I am hopeful this will also avoid those occasional double-service-init exceptions we see.  I think those might have been triggered by multiple clicks getting through here and running the submit code twice.  Will keep my eye out to see if they ever recur.

**Pull request merged**
