### PR TITLE
Upgrade to React 17

### PR DESCRIPTION
**Pull request by lbwexler**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Not entirely sure why the two tiny adjustments in this branch were necessary -- still investigating, but for some reason the Icon displayName not being trampolined to the memo wrapper as expected. 

Other than that, ran through all of toolbox on this without incident.

**Comment by lbwexler** [comment]
Seeing a number of these in the mobile App:  Not sure if we need to do anything there.

react_devtools_backend.js:2430 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DateInput

**Comment by TomTirapani** [comment]
Looks like this is coming from `react-dates` - we're on the latest version of that (v21.8.0).

FWIW, I see the same warning with React v16.13.1, and the mobile DateInput seems to function fine despite the warnings.

**Comment by lbwexler** [comment]
I think this is now good to merge, but we might also consider skipping and going straight to mobx6 which.

**Comment by lbwexler** [comment]
Tested this more, including on device.  Merging.

**Pull request merged**
