### PR TITLE
Allow elements as parameters to getRelativeTimestamp

### PR DESCRIPTION
**Pull request by peterjcoffman**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- N/A Reviewed and tested on Mobile, or determined not required.
- N/A Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
Maybe `emptyDisplay` and `equalDisplay`.?

Also, no need to call out {Element | string}.  The auto-coercion that happens from a string to an element is built-in react behavior that is well-understood...

**Comment by peterjcoffman** [comment]
>Maybe emptyDisplay and equalDisplay.?

We certainly can do that, but that would make this a breaking change.

We're already changing `nowString` to `equalString` in Hoist 29. Changing that to `equalResult` is not a breaking change, but changing `emptyResult` would be.

**Comment by haynesjm42** [comment]
> Also, no need to call out {Element | string}. The auto-coercion that happens from a string to an element is built-in react behavior that is well-understood...

I had requested that change because we do `{Element|string}` elsewhere and wouldn't want the caller to think they _have_ to provide an element to what appears to be a formatter function..

**Comment by lbwexler** [comment]
Got it re: Element | string.  Sorry to muddy the waters there.  We can redo that globally at anytime (or not)

**Comment by amcclain** [comment]
Do we have a clear decision on who is approving this and if / when we are moving forwards?

**Comment by haynesjm42** [comment]
I don't think so - I think I would prefer the display logic and customization to be in the component, instead of the `getRelativeTimestamp` function, it just doesn't feel right to have the function doing that.

Also if we aren't worried about having a green "OK" for the "equals" state in a certain client app, we can ignore this for now

**Comment by lbwexler** [comment]
I would like to continue to be involved with this -- John can you and I discuss today?  This warrants a discussion.

**Pull request closed without merging**
