### PR TITLE
Prevent 'mousedown' events within Select from closing Popovers.

### PR DESCRIPTION
**Pull request by TomTirapani**
Prevent 'mousedown' events within Select from closing Popovers.
See issue https://github.com/xh/hoist-react/issues/3516

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by lbwexler** [comment]
This is a great change.  Do we think there are a number of workarounds in place that could be unwound?  If so, I think we should mention this in changelog.

**Comment by TomTirapani** [comment]
Yeah, there’s definitely a few places in client apps where this could be carefully unwound. Will add a changelog entry when I get back to my deskOn 3 Nov 2023, at 15:19, Lee Wexler ***@***.***> wrote:﻿
This is a great change.  Do we think there are a number of workarounds in place that could be unwound?  If so, I think we should mention this in changelog.

**Comment by TomTirapani** [comment]
Added CHANGLOG

**Comment by lbwexler** [comment]
👍🏻  thanks Tom!

**Pull request merged**
