### PR TITLE
Make Cube.info metadata directly observable.

### PR DESCRIPTION
**Pull request by TomTirapani**
See issue #2178

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Review by amcclain — APPROVED** [review]
This looks good to me - and great that we were able to clean up the trampolining of info to `View`. Although that did make me a bit concerned that we had done that in the first place - i.e. that there is some subtle reason why that was preferable to what we now have here.

@lbwexler do you have any thoughts or recollections?

**Comment by lbwexler** [comment]
yes, this was quite intentional, as the deleted comment indicates.  Idea being that a disconnected view is a snapshot of data at a given time, and you would like to similarly snapshot the info (e.g. timestamps) at that time as well.

Just as a view captures a snapshot of the cube data in 'result' it should capture the immutable state of the info at that time.

**Comment by TomTirapani** [comment]
Makes sense - apologies for missing that subtlety.

I've reverted the change to CubeView, so its info is still a snapshot of the info at the time it was loaded.

**Comment by lbwexler** [comment]
Thanks Tom!

**Pull request merged**
