### PR TITLE
Allowing grid to reset without a StateModel

### PR DESCRIPTION
**Pull request by febbraiod**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by febbraiod** [comment]
Briefly reviewed with Lee. He wants to think about the approach.

**Comment by lbwexler** [comment]
Tom -- can you take a look and give your thoughts on this?  I was hoping for something simple that would just get us the restore ability in all grids.

**Comment by TomTirapani** [comment]
Looks good to me.

Did we consider saving the entire constructor params as e.g. `this.initialConfig`? Would mean we wouldn't need the `saveInitialConfigs()` method, and may be useful generally to know how a model was configured.

I think Ext had a pretty baked in concept of keeping `initialConfigs` around.

**Comment by lbwexler** [comment]
This one makes me a little nervous -- also feel like its a bit unfortunate that we don't have a way to 'clear' this config when are saving it in the dashboard, as we do in some client apps -- this changes would just write out the default, I think.

**Comment by lbwexler** [comment]
Looks like we forgot the mobile  col chooser here.

**Comment by febbraiod** [comment]
Glad to fix? Are we running with this approach?

**Pull request merged**
