### PR TITLE
Data view enhancements

### PR DESCRIPTION
**Pull request by petradish**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- N/A Reviewed and tested on Mobile, or determined not required.
- [ ] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by peterjcoffman** [comment]
You should set this as a PR on develop, not on groupedDataViews. These are really two separate sets of changes.

**Comment by amcclain** [comment]
Hi - some questions related to git more than anything - 

* Is the goal of this PR is to combine two feature branches? I.e. take some additional updates from the `DataViewEnhancements` branch and move them over to `groupedDataViews` so we can look at `groupedDataViews` as the overall feature we want to evaluate and merge into develop? That's perfectly valid, just a bit unusual, so I wanted to be sure that was what you intended
*  Are you rebasing commits from develop onto this branch, causing those commits to show up as part of this PR? I find it confusing to see unrelated (e.g. pinPad) commits in the commit stream here. I recommend using _merge commits_ to pull updates from the develop mainline *into* feature branches so you can keep them up-to-date while still keeping the commit log on PRs like this one focused on the feature on which we're working. Then when we go to merge the PR back into develop (or whatever its destination branch is), we almost always want to use a _squash commit_ to collapse the PR's changes down into a single logical commit that expresses what we wanted to get done. That way we end up with as clear and readable a commit log as possible for developers to scan over when evaluating what changed between releases, or what has changed on develop since the last release.
* What are the "g" commit messages about? 😄 

Hopefully that is clear - happy to discuss in more detail, as there are a million ways to do things in git and no clearly "right" way. Ultimately, from my point of view, I like to pop into this PRs and see what is being worked on, and in this case it was difficult to tell exactly what this was. (But - I am sure it's good stuff!)

**Comment by petradish** [comment]
Hi!
- Yes, that was my intention -- to lump these changes together as an overall DataViewModel enhancement. 
- Thanks for explaining this git workflow. I am a n00b.
- Let's just say "g" stands for growing pains. I honestly am not sure how it ended up there.
Happy to discuss today and sort it out!
Thanks,
Petra

**Comment by amcclain** [comment]
Closing this out - we're merging all DV improvements via the `groupedDataViews` branch.

**Pull request closed without merging**
