### PR TITLE
Round relative sizes to 2dp in DashContainer state.

### PR DESCRIPTION
**Pull request by TomTirapani**
See issue https://github.com/xh/hoist-react/issues/2126

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by amcclain** [comment]
I wasn't sure where in the process this rounding was happening. 

Any sense that we should ensure all of our rounded relative sizes still add to 100%  (i.e. by adjusting the last item), or is this all so close enough that it doesn't really matter? Are the width and height values that are being rounded percentage-based at this point, or are they pixel widths?  

Asking more for my own education than anything else. I think I've spent a bit too much time talking about trading allocations recently where questions around "extra pennies" keep popping up. 😄

**Comment by TomTirapani** [comment]
They're percentage sizes at this point - pixel sizes are an extra layer we added on top of GoldenLayout, which deals exclusively in relative sizes.

I *think* since we're just losing precision and not doing any math operations, they'll always add to 100? My understanding is that floating point issues come up when doing math operations, but rounding is pretty safe (but I may be wrong)

**Comment by lbwexler** [comment]
I think that we are not rounding to integers -- still storing 2 dps of precision, so things are going to come out pretty damn near 100%, and almost certainly something that is going to round to 100 when rounded to an integer.
  
So probably not much different than what we have now (which probably also will add to something close to 100 and then round to 100) except just truncating the excess precision.

If this works well in practice, think we should merge it.

**Comment by amcclain** [comment]
Great - I am all for it, and have no interest in holding it up!

My only (purely theoretical) concern was something along the lines of the sum rounding up to 101% of total and ending up triggering horizontal scrollbars or something like that with a tiny overflow. But my guess is that's not really how things work, and again if we ever see such a thing we can address then.

Thanks for the fix - I know we've had similar cases in the past and it's nice to have those specs not carry crazy precision around with them for no reason.

**Pull request merged**
