### PR TITLE
Col group borders

### PR DESCRIPTION
**Pull request by ghsolomon**
Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [ ] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by TomTirapani** [comment]
Looks great! 100% agree that it should be the default :)

Same (minor) concerns about removing borders that I posted in https://github.com/xh/hoist-react/pull/3501, but otherwise the CSS looks great 👍

**Comment by lbwexler** [comment]
greg -- is the problem that we saw with cell borders being effected taken care of?  Would love to merge this today with whatever fixes are needed.

**Comment by ghsolomon** [comment]
> greg -- is the problem that we saw with cell borders being effected taken care of? Would love to merge this today with whatever fixes are needed.

Yes, that's taken care of

**Comment by ghsolomon** [comment]
> Looks great! 100% agree that it should be the default :)
> 
> Same (minor) concerns about removing borders that I posted in #3501, but otherwise the CSS looks great 👍

Thanks @TomTirapani! I removed the border entirely since leaving it transparent caused there to be little gaps between each row (see screenshot).  Happy to change it though.

row gaps

**Comment by TomTirapani** [comment]
Thanks, got it! In that case let's stick with removing the borders - typically users are not going to change these dynamically, and better to have it look good for the 99% case 👍

**Pull request merged**
