### PR TITLE
Blueprint5 Upgrade

### PR DESCRIPTION
**Pull request by cnrudd**
Will resolve issue: https://github.com/xh/hoist-react/issues/3583

Run with toolbox branch `blueprint5`.

Toolbox PR: https://github.com/xh/toolbox/pull/698

All runs.  Still need to go through the UI with a fine tooth comb, but looking good.

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

**Comment by cnrudd** [comment]
Getting `contextMenuSingleton.js:56 Warning: ReactDOM.render is no longer supported in React 18.` on Dash Container context menu.  Will look into it next week.

**Comment by cnrudd** [comment]
Portal 5.0 changes (https://github.com/palantir/blueprint/wiki/Portal-5.0-changes):  no uses of legacy context api found in our code, so no changes needed.

**Comment by cnrudd** [comment]
overlaysProvider now wraps desktop app as per [Blueprint 5 recommendation](https://blueprintjs.com/docs/#core/components/overlay2.usage)

**Comment by cnrudd** [comment]
I wonder if we should buy into `[BlueprintProvider](https://blueprintjs.com/docs/#core/context/blueprint-provider)` at the AppContainer level?

**Comment by cnrudd** [comment]
@amcclain I experimented with removing our small blueprint icon list from hoist-dev-utils and then trying to get webpack to drop all of the unused BP icons.  I could not get webpack to drop them.  I'm not sure what we are doing wrong in our webpack config.  I yarn linked hoist-dev-utils to my toolbox project, and exporimented with various flags.  None resulted in dropping the icons.  I do know that my flags were being read, ie: linking was working.
It seems like out list of icons does not need any changes, when it is being used.   I did not see any missing icons.

**Comment by cnrudd** [comment]
> I wonder if we should buy into [`BlueprintProvider`](https://blueprintjs.com/docs/#core/context/blueprint-provider) at the AppContainer level?

After discussion with @lbwexler I've replaced `hotkeysProvider` and `overlaysProvider` in `appContainer` with `blueprintProvider`.

**Comment by Ryanseanlee** [comment]
I wanted to point out BP5 now uses Popover2 from BP4 as 'Popover'. The most notable change is it no longer supports the 'target' prop. It now uses children, so our 'item'/'items' can be used in place of the target prop. This is a breaking change.

[BP5 Popover](https://blueprintjs.com/docs/#core/components/popover)
[BP4 Popover](https://blueprintjs.com/docs/versions/4/#core/components/popover)
[BP4 Popover2](https://blueprintjs.com/docs/versions/4/#popover2-package/popover2)

**Comment by lbwexler** [comment]
thanks for the comment -- its in the the changelog, but we will definitely clarify!

**Comment by cnrudd** [comment]
> While re-testing with the latest libs and changes from the main branch in a client app, I came across this issue:
> 
> I tried running the latest BP5 snapshot, with an all new yarn.lock and modules, and I was getting a lot of "LegacyRef" errors around buttons. I found i had pulled in this version of "@types/react": "18.2.64" which has these changes: [DefinitelyTyped/DefinitelyTyped@2bcc7e7](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2bcc7e759889c24eff2891949c18dcabfc38d888) When pinned back to "resolutions": { "@types/react": "18.2.60" } the problems went away.
> 
> Resolutions can be a permanent fix.
> 
> This issue [DefinitelyTyped/DefinitelyTyped#68720](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68720), which prompted that @types/react pr, discusses some solutions component writers implemented to get rid of the TS errors. We may eventually have to apply one of them around where we set up our ForwardRef wrapper in core, or maybe we can rework our handling of the ref in our button which wraps the BP button.
> 
> I will look into reproducing this issue in toolbox and finding a solution.

This issue can be reproduced reliably in toolbox by deleting all node_modules and yarn.lock's and rerunning yarn.

Pinning both hoist-react and toolbox to

  "resolutions": {
    "@types/react": "18.2.60"
  }
  
  avoids the issue.  Anything after 18.2.60 recreates the issue.

**Comment by cnrudd** [comment]
I have solution coded that I will review with @lbwexler this afternoon.

**Comment by cnrudd** [comment]
Some coming changes to keep in mind as the year moves on:
https://x.com/acdlite/status/1758229889595977824?s=20
https://react.dev/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024

**Comment by cnrudd** [comment]
> I have a solution coded that I will review with @lbwexler this afternoon.

Review with @lbwexler .  Committed fix.  PR back on track.

**Pull request merged**
